package by.tc.task01.entity.criteria;

public final class SearchCriteria {
	
	public static enum Oven{
		MANUFACTURER, POWER_CONSUMPTION, WEIGHT, CAPACITY, DEPTH, HEIGHT, WIDTH, PRICE
	}
	
	public static enum Laptop{
		MANUFACTURER, BATTERY_CAPACITY, OS, MEMORY_ROM, SYSTEM_MEMORY, CPU, DISPLAY_INCHS, PRICE
	}
	
	public static enum Refrigerator{
		MANUFACTURER, POWER_CONSUMPTION, WEIGHT, FREEZER_CAPACITY, OVERALL_CAPACITY, HEIGHT, WIDTH, PRICE
	}
	
	public static enum VacuumCleaner{
		MANUFACTURER, POWER_CONSUMPTION, FILTER_TYPE, BAG_TYPE, WAND_TYPE, MOTOR_SPEED_REGULATION, CLEANING_WIDTH, PRICE
	}
	
	public static enum TabletPC{
		MANUFACTURER, BATTERY_CAPACITY, DISPLAY_INCHES, MEMORY_ROM, FLASH_MEMORY_CAPACITY, COLOR, PRICE
	}
	
	public static enum Speakers{
		MANUFACTURER, POWER_CONSUMPTION, NUMBER_OF_SPEAKERS, FREQUENCY_RANGE, CORD_LENGTH, PRICE
	}
	
	private SearchCriteria() {}
}

